"""Every per-host file is generated from three sources:

    rules/tradefloor.md    the desk protocol          -> AGENTS.md and Antigravity rules
    roles/*.md             the desk roles             -> Claude Code and portable agents, skill references
    server/pyproject.toml  version, and SERVER below  -> every manifest and MCP config

`python tools/build.py` writes them; `python tools/build.py --check` fails on drift.
Never edit a generated file; each one says so at the top where its format allows.
Standard library only, so it runs before the server's dependencies are installed.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTE = "Generated by tools/build.py from {src}. Edit the source and run `python tools/build.py`."

NAME = "tradefloor"
DESCRIPTION = (
    "A trading desk for any market: analysts, bull/bear debate, trader, risk committee and "
    "portfolio manager over deterministic, point-in-time market data. Direction with "
    "calibrated probabilities, a sized trade plan, and a journal that scores every call."
)
AUTHOR = {"name": "Himanshu Jangir", "url": "https://github.com/HimanshuJ16"}
REPO = "https://github.com/HimanshuJ16/tradefloor"
KEYWORDS = ["trading", "stocks", "indices", "multi-agent", "mcp", "global-markets", "technical-analysis", "research"]

SKILLS = {
    "analyze": "Full desk analysis of one instrument: direction, probabilities, trade plan, reasoning",
    "scout": "Find intraday momentum stocks in a market and run them through the desk",
    "direction": "Quick quant-only direction, range and plan for one instrument",
    "scan": "Rank a watchlist by tilt versus each instrument's own base rate",
    "review": "Score past calls: hit rate and Brier score against the base rate",
}

# Env vars the server reads, and the Claude Code userConfig key that feeds each.
ENV_FROM_USER_CONFIG = {
    "TRADEFLOOR_DEFAULT_MARKET": "default_market",
    "TRADEFLOOR_DEFAULT_HORIZON": "default_horizon",
    "TRADEFLOOR_CAPITAL": "capital",
    "TRADEFLOOR_RISK_PCT": "risk_per_trade_pct",
    "TRADEFLOOR_MAX_POSITION_PCT": "max_position_pct",
    "TRADEFLOOR_DEBATE_ROUNDS": "debate_rounds",
    "TRADEFLOOR_INTRADAY_RISK_PCT": "intraday_risk_pct",
}


def version() -> str:
    text = (ROOT / "server" / "pyproject.toml").read_text(encoding="utf-8")
    return re.search(r'^version = "([^"]+)"', text, re.M).group(1)


def server_args(root: str) -> list[str]:
    """How every host launches the server. `root` is the host's plugin-root expression.

    `python -m`, not the `tradefloor-mcp` console script: on Windows a running server locks
    its script's .exe, and uv rewrites console scripts whenever it reinstalls the package,
    so a second session or an update would fail to start while the first one runs."""
    return ["run", "--quiet", "--project", f"{root}/server", "python", "-m", "tradefloor.server"]


def lf(text: str) -> str:
    return text.replace("\r\n", "\n")


def read(rel: str) -> str:
    return lf((ROOT / rel).read_text(encoding="utf-8"))


def js(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def meta(**extra) -> dict:
    return {"name": NAME, "version": version(), "description": DESCRIPTION, "author": AUTHOR,
            "homepage": REPO, "repository": REPO, "license": "MIT", "keywords": KEYWORDS, **extra}


# ---------------------------------------------------------------- roles

def parse_role(path: Path) -> dict:
    m = re.match(r"---\n(.*?)\n---\n\n?(.*)", lf(path.read_text(encoding="utf-8")), re.S)
    fm = dict(line.split(": ", 1) for line in m.group(1).splitlines())
    fm["body"] = m.group(2).rstrip() + "\n"
    fm["src"] = f"roles/{path.name}"
    return fm


def roles() -> list[dict]:
    return [parse_role(p) for p in sorted((ROOT / "roles").glob("*.md"))]


def _fm(fields: dict) -> str:
    return "---\n" + "\n".join(f"{k}: {v}" for k, v in fields.items()) + "\n---\n"


def agent_portable(r: dict) -> str:
    # name + description only: the subset Gemini CLI, Devin, Cursor and Grok all accept.
    return _fm({"name": r["name"], "description": r["description"]}) + f"\n<!-- {NOTE.format(src=r['src'])} -->\n\n" + r["body"]


def agent_claude(r: dict) -> str:
    denied = "Bash, Edit, NotebookEdit" + (", WebSearch, WebFetch" if r["web"] == "never" else "")
    return _fm({
        "name": r["name"], "description": r["description"],
        "model": "inherit" if r["tier"] == "deep" else "sonnet",
        "disallowedTools": denied, "color": r["color"],
    }) + f"\n<!-- {NOTE.format(src=r['src'])} -->\n\n" + r["body"]


DESK_SKILLS = {"analyze": ["analyze"], "scout": ["scout"], "both": ["analyze", "scout"]}


def role_reference(r: dict) -> str:
    return (f"<!-- {NOTE.format(src=r['src'])} -->\n\n# Role: {r['name']}\n\n"
            f"Play this role yourself when your host has no `{r['name']}` subagent.\n\n" + r["body"])


# ---------------------------------------------------------------- rules copies

def _plain(body: str) -> str:
    return f"<!-- {NOTE.format(src='rules/tradefloor.md')} -->\n\n{body}"


def _with_fm(fm: str, body: str) -> str:
    return f"---\n{fm}\n---\n\n<!-- {NOTE.format(src='rules/tradefloor.md')} -->\n\n{body}"


RULE_DESC = "tradefloor trading desk: when asked where a stock, index, future, FX pair or crypto asset is heading, or whether to buy or sell it"

RULE_TARGETS = {
    "AGENTS.md": _plain,  # Codex, Antigravity, and any agent that reads AGENTS.md
    ".agents/rules/tradefloor.md": _plain,  # Antigravity workspace rules
}


# ---------------------------------------------------------------- manifests and MCP configs

def claude_plugin() -> dict:
    user_config = {
        "default_market": {"type": "string", "title": "Home market", "default": "US",
                           "description": "Exchange code for bare tickers (RELIANCE -> RELIANCE.NS for NSE). US, NSE, BSE, LSE, XETRA, EPA, AMS, TSE, HKEX, SSE, SZSE, KRX, TWSE, SGX, ASX, TSX, B3, JSE and more."},
        "default_horizon": {"type": "string", "title": "Default horizon", "options": ["1w", "2w", "1m", "3m", "6m", "1y"], "default": "1m",
                            "description": "Forecast and holding horizon when none is given."},
        "capital": {"type": "number", "title": "Trading capital", "default": 0, "min": 0,
                    "description": "Account size in your home currency, for position sizing. 0 skips sizing."},
        "risk_per_trade_pct": {"type": "number", "title": "Risk per trade (%)", "default": 1, "min": 0.1, "max": 5,
                               "description": "Percent of capital lost if the stop is hit. 0.5 to 1 is a common professional range."},
        "max_position_pct": {"type": "number", "title": "Max position size (%)", "default": 20, "min": 1, "max": 100,
                             "description": "Cap on a single position as a percent of capital, whatever the stop distance."},
        "intraday_risk_pct": {"type": "number", "title": "Intraday risk per trade (%)", "default": 0.5, "min": 0.05, "max": 3,
                              "description": "Percent of capital lost if an intraday stop is hit. Used by /tradefloor:scout."},
        "debate_rounds": {"type": "number", "title": "Bull/bear debate rounds", "default": 1, "min": 1, "max": 3,
                          "description": "Rounds in the researcher debate for a standard run. Deep runs add one. Each round is two more agent calls."},
    }
    return {
        "$schema": "https://json.schemastore.org/claude-code-plugin-manifest.json",
        **meta(displayName="tradefloor"),
        "agents": [f"./hosts/claude/agents/{r['name']}.md" for r in roles()],
        "mcpServers": {NAME: {
            "command": "uv", "args": server_args("${CLAUDE_PLUGIN_ROOT}"),
            "env": {k: "${user_config." + v + "}" for k, v in ENV_FROM_USER_CONFIG.items()},
        }},
        "userConfig": user_config,
    }


def marketplace(schema: str | None, category: str) -> dict:
    out = {"name": NAME, "description": "tradefloor: a multi-agent trading desk for any market.",
           "owner": {"name": "Himanshu Jangir", "url": "https://github.com/HimanshuJ16"},
           "plugins": [{"name": NAME, "source": "./", "description": DESCRIPTION, "category": category,
                        "tags": ["trading", "stocks", "indices", "multi-agent", "global-markets"]}]}
    return {"$schema": schema, **out} if schema else out


def agent_plugin() -> dict:
    """Agent Plugins 1.0 root manifest: Codex, Copilot CLI, Cursor, Devin, VS Code and other conforming clients."""
    return {
        "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
        **meta(),
        "extensions": {"com.openai": {"interface": codex_interface()}},
    }


def agent_plugin_mcp() -> dict:
    return {"$schema": "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
            "mcpServers": {NAME: {"type": "stdio", "command": "uv", "args": server_args("${PLUGIN_ROOT}")}}}


def codex_interface() -> dict:
    return {
        "displayName": "tradefloor",
        "shortDescription": "Trading desk for any market",
        "longDescription": "Analysts, a bull/bear debate, a trader, a risk committee and a portfolio manager over point-in-time market data for any exchange. Direction with probabilities, a sized plan, and a scored journal.",
        "developerName": "Himanshu Jangir",
        "category": "Productivity",
        "capabilities": ["Skills", "MCP"],
        "websiteURL": REPO,
        "defaultPrompt": ["Where is the Nifty 50 heading this month?", "Which Nifty 50 stocks have strong intraday momentum right now?", "How have my past tradefloor calls done?"],
        "brandColor": "#0B6E4F",
    }


def codex_plugin() -> dict:
    return {**meta(), "skills": "./skills/", "mcpServers": "./mcp.json", "interface": codex_interface()}


def antigravity_mcp() -> dict:
    # Antigravity reads mcp_config.json from a plugin root but, as of agy 1.1.16, expands no
    # path variable and starts servers in the workspace. So its plugin fetches the server by
    # git URL, pinned to this release's tag. tools/install.py antigravity is the local route.
    src = f"git+{REPO}@v{version()}#subdirectory=server"
    return {"mcpServers": {NAME: {"command": "uvx", "args": ["--from", src, "tradefloor-mcp"]}}}


# ---------------------------------------------------------------- the full set

def targets() -> dict[str, str]:
    out: dict[str, str] = {}
    body = read("rules/tradefloor.md")
    for path, render in RULE_TARGETS.items():
        out[path] = render(body)
    for r in roles():
        out[f"agents/{r['name']}.md"] = agent_portable(r)
        out[f"hosts/claude/agents/{r['name']}.md"] = agent_claude(r)
        for skill in DESK_SKILLS[r["desk"]]:
            out[f"skills/{skill}/references/{r['name']}.md"] = role_reference(r)
    out[".claude-plugin/plugin.json"] = js(claude_plugin())
    out[".claude-plugin/marketplace.json"] = js(marketplace("https://json.schemastore.org/claude-code-marketplace.json", "finance"))
    out["plugin.json"] = js(agent_plugin())  # Agent Plugins 1.0: Codex; Antigravity requires it
    out["mcp.json"] = js(agent_plugin_mcp())  # Codex, via .codex-plugin/plugin.json
    out[".codex-plugin/plugin.json"] = js(codex_plugin())
    out["mcp_config.json"] = js(antigravity_mcp())  # Antigravity plugins read this name
    return out


# Generated directories: a file inside them that no longer has a source is stale.
GENERATED_DIRS = ["agents", "hosts/claude/agents", "skills/analyze/references", "skills/scout/references"]
